name: Lint

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  golang-ci:
    name: GolangCi-Lint
    runs-on: ubuntu-latest
    steps:
      # optionally use a specific version of Go rather than the default one
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with: # BUG: typecheck error when enable all
          args: --disable-all -E goimports,misspell,whitespace
          version: latest
